Style/StringLiterals:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Enabled: false

Layout/TrailingEmptyLines:
  Enabled: true

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
