# frozen_string_literal: true

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/*'
    - 'db/schema.rb'
    - 'db/queue_schema.rb'
  TargetRubyVersion: 3.3

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Max: 200

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space

Layout/TrailingEmptyLines:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Lint/UselessAssignment:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false

require:
  - rubocop-rails
  - rubocop-performance
  - rubocop-rspec
