# frozen_string_literal: true

AllCops:
  NewCops: enable
  TargetRubyVersion: 3.3
  Exclude:
    - "bin/*"
    - "db/schema.rb"
    - "db/queue_schema.rb"
  # RuboCop extensions (plugin形式)
  Plugins:
    - rubocop-rails
    - rubocop-performance
    - rubocop-rspec

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Layout/LineLength:
  Max: 200

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: space

Layout/TrailingEmptyLines:
  Enabled: true

Style/StringLiterals:
  EnforcedStyle: double_quotes

Lint/UselessAssignment:
  Enabled: false

Rails/I18nLocaleTexts:
  Enabled: false

Rails/BulkChangeTable:
  Enabled: false
