default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: protein_map_app_development

test:
  <<: *default
  database: protein_map_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>

  queue:
    adapter: redis
    url: <%= ENV['REDIS_URL'] %>
